version: "3"
services:
  frontend:
    stdin_open: true
    tty: true
    build: ./my-app
    ports:
      - 3000:3000
      - 8080:3000
    volumes:
      - /app/node_modules
      - ./my-app/:/app
    depends_on:
      - backend
  backend:
    build: ./api
    restart: always
    env_file:
      - /api/.env.local
    ports:
      - 5050:5050
    volumes:
      - ./api/:/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db/:/data/db/ 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
