name: api-build

on:
  push:
    paths:
      - ".github/workflow/api-build.yml"
      - "demo/my-dotnet/**"
  workflow_dispatch: # manualy

jobs:
  build:
    name: build dotnet api 
    runs-on: ubuntu-latest
    steps:
      - run: pwd && ls -al
      - uses: actions/checkout@v4
      - run: pwd && ls -al
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        working-directory: ./demo/my-dotnet
      - run: dotnet test
        working-directory: ./demo/my-dotnet


