name: api-build

on:
  push:
    paths:
      - ".github/workflow/api-build.yml"
      - "demo/**"
  workflow_dispatch: # manualy

jobs:
  build:
    name: Build dotnet api 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        working-directory: ./demo

