name: cd-azure

on:
  push:
    paths:
      - ".github/workflows/cd-azure.yml"
      - "demo/my-dotnet/**"
  workflow_dispatch: # manual

jobs:
  
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/my-dotnet

    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all commits, so we can generate version off of tags/commit sha...
        
      -
        name: set up docker buildx 
        uses: docker/setup-buildx-action@v3

      - 
        name: build docker 
        run: docker buildx ls

      - 
        name: login to docker hub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - 
        name: publish doker
        run: ./build-push.sh # can reuse local build scripts for CI/CD        
        
  # deploy:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: production
  #     url: ${{ steps.deploy.outputs.webapp-url }}
  #   needs: build
  #   steps:
  #     - uses: azure/login@v2
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
  #     - uses: azure/webapps-deploy@v3
  #       id: deploy
  #       with:
  #         app-name: gh-actions-web-api
  #         images: weshigbee/actions-web:latest
  #         resource-group-name: gh-actions
