# https://github.com/g0t4/course-gh-actions/blob/main/.github/workflows/upper-cross.yml
name: upper-cross

on:
  push:
    paths:
      - ".github/workflows/upper-cross.yml"
      - "demo/my-go/**"
  workflow_dispatch: # manual

jobs:
  cross:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "demo/my-go/**"
    steps:
      - run: pwd
      - run: tree
      # - uses: actions/checkout@v4
      # - uses: actions/setup-go@v5
      #   with:
      #     go-version: 1.22.4
      #     cache-dependency-path: ./demo/my-go/go.sum
      # - run: ./build.xplat.sh
      # - uses: softprops/action-gh-release@v2
      #   with:
      #     files: ./upper/bin/upper*
      #     body: "Binaries for the upper (go) command line tool!!!"
      #     tag_name: ${{ github.ref_name }}
      #   if: startsWith(github.ref, 'refs/tags/')
      # # - uses: actions/upload-artifact@v4
      # #   with:
      # #     path: ./upper/bin/upper*
      # #     name: build
