name: upper-build

on:
  # push:
  #   paths:
  #     - ".github/workflows/upper-build.yml"
  #     - "demo/my-go/**"

  workflow_dispatch: # manual

jobs:
  build:    
    runs-on: macos-latest
    defaults:
      run:
        working-directory: demo/my-go
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 1.22.4
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum
      - run: ls
      - run: go build
      - run: ls
      # - run: go test -v

