name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "demo/my-go/**"

  workflow_dispatch: # manual

jobs:
  build:    
    runs-on: macos-latest
    defaults:
      run:
        working-directory: demo/my-go
    steps:
      - run: pwd && ls -al
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 1.22
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum
      - run: ls
      - run: go build
      - run: ls

