# https://github.com/g0t4/course-gh-actions/blob/main/.github/workflows/upper-cross.yml
name: upper-cross

on:
  push:
    paths:
      - ".github/workflows/upper-cross.yml"
      - "demo/my-go/**"
  workflow_dispatch: # manual

permissions: 
  packages: write
  contents: read # not needed in public repos

jobs:
  cross:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "demo/my-go/"
    steps:
      - uses: actions/checkout@v4

      - run: pwd && tree

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
          cache-dependency-path: demo/my-go/go.sum

      # git update-index --chmod=+x build.xplat.sh
      - name: Run shell script
        run: ./build.xplat.sh         
      
      - uses: softprops/action-gh-release@v2
        with:
          files: ./demo/my-go/bin/upper*
          body: "Binaries for the upper (go) command line tool!!!"
          tag_name: ${{ github.ref_name }}
        # if: startsWith(github.ref, 'refs/tags/')

      - uses: actions/upload-artifact@v4
        with:
          path: ./demo/my-go/bin/upper*
          name: build
