name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "demo/my-go/**"

  workflow_dispatch: # manual

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - run: pwd && ls -al
      - uses: actions/checkout@v4
        with:
          path: 'demo/my-go'
      - run: pwd && ls -al
      - run: du demo
      - run: go version
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.4"
          # go-version-file: demo/my-go/go.mod
      - run: go version


