name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "demo/my-go/**"

  workflow_dispatch: # manual

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - run: go version
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.4"
          go-version-file: ./demo/my-go/go.mod
          cache-dependency-path: ./demo/my-do/go.sum
      # - run: go mod download
      - run: go version
      - run: pwd && ls -al
      - uses: actions/checkout@v4
        with:
          path: 'demo/my-go/'
      - run: pwd && ls -al
      - run: du demo
      - run: |
          pwd
          ls
        #   go build
        #   ls
        working-directory: demo/my-go
        name: build and test

